# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module', '0002_auto_20170209_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=20)),
                ('name', models.CharField(default='', max_length=50)),
                ('cnname', models.CharField(default='', max_length=50)),
                ('comments', models.CharField(default='', max_length=200)),
                ('state', models.IntegerField(choices=[(1, 'used'), (2, 'forbidden')], default=1)),
                ('moduleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Module')),
            ],
            options={
                'ordering': ['no'],
            },
        ),
    ]
