# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=20)),
                ('name', models.CharField(default='', max_length=50)),
                ('cnname', models.CharField(default='', max_length=50)),
                ('comments', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
