# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_user', '0001_initial'),
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('objectid', models.IntegerField()),
                ('detail', models.TextField(default='')),
                ('actionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action.Action')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_user.CustomUser')),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
    ]
