# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-createtime']},
        ),
        migrations.RenameField(
            model_name='log',
            old_name='datetime',
            new_name='createtime',
        ),
    ]
