# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('game', '0001_initial'),
        ('node', '0001_initial'),
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='games',
            field=models.ManyToManyField(related_name='user2game', to='game.Game'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nodes',
            field=models.ManyToManyField(related_name='user2node', to='node.Node'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(related_name='user2role', to='role.Role'),
        ),
    ]
