# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cnname', models.CharField(max_length=50, unique=True)),
                ('comments', models.CharField(default='', max_length=200)),
                ('state', models.IntegerField(choices=[(1, 'used'), (2, 'forbidden')], default=1)),
                ('actions', models.ManyToManyField(related_name='role2action', to='action.Action')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
