# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes_template', '0002_auto_20170222_1301'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game2nodestemplate',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='game2nodestemplate',
            name='gameid',
        ),
        migrations.RemoveField(
            model_name='game2nodestemplate',
            name='nodestemplate',
        ),
        migrations.AddField(
            model_name='game',
            name='nodestemplateid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nodes_template.NodesTemplate'),
        ),
        migrations.AlterField(
            model_name='game',
            name='comments',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.IntegerField(choices=[(1, 'default'), (2, 'done'), (3, 'cancelled')], default=1),
        ),
        migrations.DeleteModel(
            name='Game2NodesTemplate',
        ),
    ]
