# -*- coding:utf-8 -*-

"""
Django settings for WeixinTMN project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

import warnings

from conf import ProjectConfig


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%!07kvvw+mxyd4@ne329bzj1i2)=^*nm-^d5+yk4)$@c9(3z3)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'action.apps.ActionConfig',
    'config.apps.ConfigConfig',
    'custom_user.apps.CustomUserConfig',
    'document.apps.DocumentConfig',
    'game.apps.GameConfig',
    'games_template.apps.GamesTemplateConfig',
    'log.apps.LogConfig',
    'module.apps.ModuleConfig',
    'msg.apps.MsgConfig',
    'node.apps.NodeConfig',
    'nodes_template.apps.NodesTemplateConfig',
    'role.apps.RoleConfig',
    'users_group.apps.UsersGroupConfig',
    'weixin_interface.apps.WeixinInterfaceConfig',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'WeixinTMN.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'WeixinTMN.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

if 'SERVER_SOFTWARE' in os.environ:
    from sae.const import (MYSQL_HOST, MYSQL_PORT, MYSQL_USER, MYSQL_PASS, MYSQL_DB)
else:
    #MYSQL_HOST = 'w.rdc.sae.sina.com.cn'
    #MYSQL_PORT = '3306'
    #MYSQL_USER = 'mom5ozl0mm'
    #MYSQL_PASS = 'wx2mjl1mlwjw0mw25jx5z0ky2hmiy535m3mxmjyh'
    #MYSQL_DB = 'app_qusenjoy'
    #from sae._restful_mysql import monkey
    #monkey.patch()
    MYSQL_HOST = 'localhost'
    MYSQL_PORT = '3306'
    MYSQL_USER = 'root'
    MYSQL_PASS = '123456'
    MYSQL_DB = 'test'

DATABASES = {
  'default': {
    'ENGINE':  'django.db.backends.mysql',
    'NAME':  MYSQL_DB,
    'USER':  MYSQL_USER,
    'PASSWORD': MYSQL_PASS,
    'HOST':  MYSQL_HOST,
    'PORT':  MYSQL_PORT,
  }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATIC_URL = '/static/'


DEFAULT_CHARSET = 'utf-8'


warnings.filterwarnings(
    'error', r"DateTimeField .* received a naive datetime",
    RuntimeWarning, r'django\.db\.models\.fields',
)
