# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date2GamesTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GamesTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('gameids', models.TextField()),
                ('comments', models.CharField(default='', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='date2gamestemplate',
            name='gamestemplate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_template.GamesTemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='date2gamestemplate',
            unique_together=set([('date', 'gamestemplate')]),
        ),
    ]
