# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170222_1301'),
        ('games_template', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestemplate',
            name='gameids',
        ),
        migrations.AddField(
            model_name='gamestemplate',
            name='gameids',
            field=models.ManyToManyField(related_name='gamestemplate2game', to='game.Game'),
        ),
    ]
