# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField(choices=[(1, 'template'), (2, 'instance')])),
                ('deadline', models.DateTimeField(null=True)),
                ('notifytime', models.IntegerField(default=5)),
                ('comments', models.CharField(default='', max_length=200)),
                ('state', models.IntegerField(choices=[(1, 'nouse'), (2, 'unfinished'), (3, 'broken'), (4, 'done')])),
                ('gameid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='NodeRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childnode', to='node.Node')),
                ('parentnodeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentnode', to='node.Node')),
            ],
            options={
                'ordering': ['nodeid'],
            },
        ),
        migrations.CreateModel(
            name='NodesLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'normal'), (2, 'broken')])),
                ('nextnodeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linenextnode', to='node.Node')),
                ('prevnodeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineprevnode', to='node.Node')),
            ],
            options={
                'ordering': ['prevnodeid'],
            },
        ),
    ]
