# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='gameid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game2node', to='game.Game'),
        ),
        migrations.AlterField(
            model_name='node',
            name='state',
            field=models.IntegerField(choices=[(1, 'nouse'), (2, 'unfinished'), (3, 'broken'), (4, 'done')], default=2),
        ),
        migrations.AlterField(
            model_name='noderelationship',
            name='parentnodeid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentnode', to='node.Node'),
        ),
    ]
