# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
        ('users_group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersgroup',
            name='nodes',
            field=models.ManyToManyField(related_name='usersgroup2node', to='node.Node'),
        ),
    ]
